### ISSUE TITLE
Smallworld and Xoops 2.5.7.1

### ISSUE THREAD

**Issue by cesagonchu** [djculex/smallworld#1]
I especially hope that health goes well for you and your family. :-)

I just tested your great module on Xoops 2.5.7.1 and I get some errors.

After a brand new installation, when I go on the user side page (/modules/smallworld/), I get these 2 errors:

Warning: array_unique() expects parameter 1 to be array, null given in file /modules/smallworld/class/publicWall.php line 75

Warning: Invalid argument supplied for foreach() in file /modules/smallworld/include/functions.php line 120

I downloaded the module here:

http://sourceforge.net/p/xoops/svn/HEAD/tree/XoopsModules/smallworld/trunk/

because you haven't updated on Github.

___

My config:

PHP: 5.6.4-4ubuntu6.2
MYSQL: 5.6.25-0ubuntu0.15.04.1
XOOPS: 2.5.7.1

Xoops and the module are in english

**Comment by cesagonchu** [comment]
UP!

**Comment by djculex** [comment]
Aw sorry Cesag I haven't forgot. Just a little busy these days. Hope to get a look at it this weekend :-)

**Comment by cesagonchu** [comment]
Tyvm! ;-)
And it's Cesagonchu now :-P
http://xoops.org/modules/newbb/viewtopic.php?topic_id=77009

**Comment by cesagonchu** [comment]
UP!

**Comment by djculex** [comment]
@cesagonchu Should be some fixes and added feautures now. At least a bit more up to date ;-)

**Comment by cesagonchu** [comment]
Wonderful, I'm looking forward to that. I will test soon. Thanks again! ;-)
