### ISSUE TITLE
permission

### ISSUE THREAD

**Issue by cesagonchu** [djculex/smallworld#2]
After installing smallworld, when I go to user side (/modules/smallworld/), I get this error:

Sorry, you don't have the permission to access this area.

However, when I go to group permissions, I have the rights:

![image](https://cloud.githubusercontent.com/assets/4613970/10154466/bf95399e-6667-11e5-8d8f-c788f2955159.png)

My config:

PHP version: 5.6.4-4ubuntu6.2
MYSQL version: 5.6.25-0ubuntu0.15.04.1
XOOPS version: 2.5.7.1

**Comment by djculex** [comment]
Strange error I thought was long gone. You should now get the smallworld popup for extended register instead of the no permission.

**Comment by cesagonchu** [comment]
Thank you, it works now, you can close this issue :-)
