### ISSUE TITLE
Undefined variable: profile

### ISSUE THREAD

**Issue by cesagonchu** [djculex/smallworld#3]
After install, when I go to user side and click to the module (/modules/smallworld/), a popup is opened but I get these errors:
Notice: Undefined variable: profile in file /modules/smallworld/index.php line 110
Notice: Undefined variable: profile in file /modules/smallworld/index.php line 118

![image](https://cloud.githubusercontent.com/assets/4613970/10175463/51dd37a2-66ef-11e5-8f18-929067a2cc8e.png)

___

My config:

PHP version: 5.6.4-4ubuntu6.2
MYSQL version: 5.6.25-0ubuntu0.15.04.1
XOOPS version: 2.5.7.1

**Comment by djculex** [comment]
Undeclared variable $profile now declared ;-)

**Comment by cesagonchu** [comment]
Thanks! :-)
