### ISSUE TITLE
undefined constant _MI_SMALLWORLD_ALL

### ISSUE THREAD

**Issue by cesagonchu** [djculex/smallworld#4]
Before installing the module on install list (modules/system/admin.php?fct=modulesadmin&op=installlist), I get this error:

Notice: Use of undefined constant _MI_SMALLWORLD_ALL - assumed '_MI_SMALLWORLD_ALL' in file /modules/smallworld/include/functions.php line 1009

**Comment by djculex** [comment]
Got it. The defines are missing in the french translation. I have added the english to french, french_iso for later translation :-)

**Comment by cesagonchu** [comment]
Ok but I only do my tests with english version :-)
For info, french iso is old, we only use french (UTF-8) now.
