### ISSUE TITLE
Undefined variable: profile

### ISSUE THREAD

**Issue by cesagonchu** [djculex/smallworld#5]
This issue is not solved:
http://github.com/djculex/smallworld/issues/3

I still have these errors:

Notice: Undefined variable: profile in file /modules/smallworld/index.php line 110
Notice: Undefined variable: profile in file /modules/smallworld/index.php line 118

**Comment by djculex** [comment]
Should be fixed now. Strange little bug

**Comment by cesagonchu** [comment]
Thanks!
After filling the form, this is what I get:
![image](https://cloud.githubusercontent.com/assets/4613970/10228042/1b4be052-6871-11e5-88d0-760a7db5636e.png)

**Comment by cesagonchu** [comment]
I have just sending you two emails.

**Comment by djculex** [comment]
Wow I'm beginning to think this is an older copy of the script. Somehow I must have lost the newest one. I'll give it a look

**Comment by djculex** [comment]
Should be ok by now. Bad thing about leaving projects like this behind for too long is that you forget what does what and why ;-)

**Comment by cesagonchu** [comment]
And I love this project! :-) No problem, we will take the time to test and correct.
